### ISSUE TITLE
Next 13 

### ISSUE THREAD

**Issue by diegomnDev** [cNoside/nextjs-mantine-template#1]
I've tried to start this template upgrading to Next 13 and fails. 
Unhandled Runtime Error
ReferenceError: Cannot access 'Layout' before initialization

Call Stack
Module.Layout
webpack-internal:///./src/shared/components/layout/index.tsx (3:47)
Number.eval
webpack-internal:///./src/shared/components/index.ts (8:260)

**Comment by ecwk** [comment]
Next 13 might have changed some webpack configurations. For some reason absolute importing components in _app.tsx causes the error.

I managed to fix this by using relative imports with components.
`shared/components/layout/navbar.component.tsx`
```tsx
// import { ToggleDark } from 'shared/components;
import { ToggleDark } from '../ui/buttons/toggle-dark.component'; 
````

I'm not entirely familar with webpack so this is the best solution I've got.
